#include "makefile_gen.h"
#include "utils.h"
#include <stdio.h>
#include <string.h>

int makefile_gen_generate(uint32_t uid, const char *module_name, const char *extra_cflags) {
    char uid_dir[32], path[256];
    format_uid_dirname(uid, uid_dir, sizeof(uid_dir));
    snprintf(path, sizeof(path), "./test/%s/Makefile", uid_dir);

    FILE *f = fopen(path, "w");
    if (!f) { log_error("Cannot write %s", path); return -1; }

    char cflags[512] = "-Wall -Wextra -std=c11";
    if (extra_cflags && extra_cflags[0]) {
        snprintf(cflags, sizeof(cflags), "-Wall -Wextra -std=c11 %s", extra_cflags);
    }

    fprintf(f, "# Auto-generated by Agent 3 for UID: %u (%s)\n", uid, module_name);
    fprintf(f, "CC = gcc\n");
    fprintf(f, "CFLAGS = %s\n", cflags);
    fprintf(f, "TARGET = test_%s.exe\n", uid_dir);
    fprintf(f, "SRCS = test_main.c\n");
    fprintf(f, "OBJS = $(SRCS:.c=.o)\n\n");
    fprintf(f, ".PHONY: all clean\n\n");
    fprintf(f, "all: $(TARGET)\n\n");
    fprintf(f, "$(TARGET): $(OBJS)\n");
    fprintf(f, "\t$(CC) $(CFLAGS) -o $@ $^\n\n");
    fprintf(f, "%%.o: %%.c\n");
    fprintf(f, "\t$(CC) $(CFLAGS) -c -o $@ $<\n\n");
    fprintf(f, "clean:\n");
    fprintf(f, "\trm -f $(OBJS) $(TARGET)\n");
    fclose(f);

    log_info("Makefile generated: %s", path);
    return 0;
}
